# Главная страница, с которой вы можете загрузить файл.
GET localhost:8080/main

###
# URL для загрузки вашего файла. Значение поля - "file".
POST localhost:8080/api/file/upload

###
# URL для скачивания вашего файла. Вместо name вставляйте свой UUID, который вы получили при загрузке файла.
GET localhost:8080/api/file/download/{name}